using System.Text.RegularExpressions;
using AssCS;

namespace Crunchymatic.Analyzers;

public static partial class PipelineAnalyzer
{
    public static PipelineAnalyzerResult Analyze(Document document, DocumentCommonAnalysis commonAnalysis,
        string rawFile)
    {
        var (pipeline, comment) = DetectPipeline(document, rawFile);
        
        return new PipelineAnalyzerResult(pipeline, comment);
    }

    private static PipelineResult DetectPipeline(Document document, string rawFile)
    {
        var match = GetScriptGeneratedByTag().Match(rawFile);

        if (match.Success)
        {
            var comment = match.Groups[1].Value;

            if (comment.Contains("Closed Caption Converter"))
            {
                return new PipelineResult(SubtitlePipeline.ClosedCaptionConverter, comment);
            }

            return new PipelineResult(SubtitlePipeline.Direct, comment.Trim('\n', '\r'));
        }

        var originalScript = document.ScriptInfoManager.Get("Original Script");

        if (originalScript != null && originalScript.Contains("http://www.crunchyroll.com/user/"))
        {
            return new PipelineResult(SubtitlePipeline.Old, null);
        }

        return new PipelineResult(SubtitlePipeline.Direct, null);
    }

    [GeneratedRegex(@"^\[Script Info\](?:\n|\r|\r\n)((?:;.*(?:\n|\r|\r\n))+)")]
    private static partial Regex GetScriptGeneratedByTag();

    private readonly record struct PipelineResult(
        SubtitlePipeline Pipeline,
        string? GeneratedByComment);
}

public record PipelineAnalyzerResult(SubtitlePipeline Pipeline, string? GeneratedByComment);

/// <summary>
/// How CR has processed the subtitle file before shipping it out.
/// </summary>
public enum SubtitlePipeline
{
    /// <summary>
    /// Lacks any "Script generated by" tags, title is the language name, Original Script: is a crunchyroll user.
    /// </summary>
    Old,

    /// <summary>
    /// Contains "Script generated by Closed Caption Converter". No overlaps, has styles called "BottomCenter" etc.
    /// </summary>
    ClosedCaptionConverter,

    /// <summary>
    /// A direct upload of the original ASS file provided by the subtitling team.
    /// Might contain "Script generated by" headers specifying the software used to author the subtitles, or Project Garbage.
    /// </summary>
    Direct,
}