using System.Text.RegularExpressions;
using AssCS;

namespace Crunchymatic.Analyzers;

public static partial class PipelineAnalyzer
{
    private static readonly string[] Srt2AssStyles =
    [
        "Default",
        "OS",
        "Italics",
        "On Top"
    ];
    
    private static readonly string[] BDDXStyles =
    [
        "BD DX",
        "Default"
    ];

    private static readonly string[] NTPActors =
    [
        "NTP",
        "On-screen Text"
    ];

    public static PipelineAnalyzerResult Analyze(Document document, DocumentCommonAnalysis commonAnalysis,
        string rawFile)
    {
        var (pipeline, comment) = DetectPipeline(document, rawFile);

        return new PipelineAnalyzerResult(pipeline, comment);
    }

    private static PipelineResult DetectPipeline(Document document, string rawFile)
    {
        var match = GetScriptGeneratedByTag().Match(rawFile);


        string? comment = null;
        if (match.Success)
        {
            comment = match.Groups[1].Value;
        }

        if (comment != null && comment.Contains("Closed Caption Converter"))
        {
            return new PipelineResult(SubtitlePipeline.ClosedCaptionConverter, comment);
        }

        var originalScript = document.ScriptInfoManager.Get("Original Script");

        if (comment == null && originalScript != null && originalScript.Contains("http://www.crunchyroll.com/user/"))
        {
            return new PipelineResult(SubtitlePipeline.Old, null);
        }

        // TODO: files can realistically both be Old and EZConvert/SRT2ASS (not seen in the wild however).
        if (document.EventManager.Events.Any(x => x.Style.Contains("Font1")))
        {
            return new PipelineResult(SubtitlePipeline.EzConvert, comment);
        }
        
        // TODO: need to break NTP out into more specific types of sub processors (e.g. toho's thing)
        if(!BDDXStyles.Except(document.StyleManager.Styles.Select(x => x.Name)).Any())
        {
            var actorNames = document.EventManager.Events.Select(x => x.Actor).Distinct();
            
            return new PipelineResult(SubtitlePipeline.NTP, comment);
        }

        // if the document's styles have at least all of Srt2Ass's styles
        if (!Srt2AssStyles.Except(document.StyleManager.Styles.Select(x => x.Name)).Any())
        {
            var actorNames = document.EventManager.Events.Select(x => x.Actor).Distinct();

            // TODO: need to figure out when to apply this. Grow Up Show - S01E02 Rus for example has basic TS and
            // doesn't have converted styles, yet still has NTP set. 
            if (!NTPActors.Except(actorNames).Any())
            {
                return new PipelineResult(SubtitlePipeline.NTP, comment);
            }

            return new PipelineResult(SubtitlePipeline.Srt2Ass, comment);
        }

        return new PipelineResult(SubtitlePipeline.Direct, null);
    }

    [GeneratedRegex(@"^\[Script Info\](?:\n|\r|\r\n)((?:;.*(?:\n|\r|\r\n))+)")]
    private static partial Regex GetScriptGeneratedByTag();

    private readonly record struct PipelineResult(
        SubtitlePipeline Pipeline,
        string? GeneratedByComment);
}

public record PipelineAnalyzerResult(SubtitlePipeline Pipeline, string? GeneratedByComment);

/// <summary>
/// How the subtitle file has been processed before shipping it out.
/// </summary>
public enum SubtitlePipeline
{
    /// <summary>
    /// Lacks any "Script generated by" tags, title is the language name, Original Script: is a crunchyroll user.
    /// </summary>
    Old,

    /// <summary>
    /// Contains "Script generated by Closed Caption Converter". No overlaps, has styles called "BottomCenter" etc.
    /// </summary>
    ClosedCaptionConverter,

    /// <summary>
    /// A direct upload of the original ASS file provided by the subtitling team.
    /// Might contain "Script generated by" headers specifying the software used to author the subtitles, or Project Garbage.
    /// </summary>
    Direct,

    /// <summary>
    /// Has styles from Crunchyroll's SRT to ASS converter.
    /// </summary>
    Srt2Ass,

    /// <summary>
    /// Has styles from EZConvert.
    /// </summary>
    EzConvert,

    /// <summary>
    /// Converted with some other unidentified tool. name derived from NTP, which appears in actor fields sometimes, and who's meaning is currently unknown
    /// </summary>
    NTP,

    Vtt,
}